import './rail-blueprint-preview.css';
import { RAIL_BRICK_STATION_PITCH } from '../bp/rail-blueprint.ts';

const viewBoxWidth = 192;
const firstStationOffset = 8;

function stationOffset(index: number): number {
  return firstStationOffset + index * RAIL_BRICK_STATION_PITCH;
}

function stationPosition(side: 'input' | 'output', index: number) {
  const offset = stationOffset(index);
  return {
    x: side === 'input' ? 4 + offset - 2 : 188 - offset + 2,
    y: side === 'input' ? 84 : 38,
  };
}

function curve(
  [startControlX, startControlY]: [number, number],
  [endControlX, endControlY]: [number, number],
  [endX, endY]: [number, number],
): string {
  return `c ${startControlX} ${startControlY}, ${endControlX + endX} ${endControlY + endY}, ${endX} ${endY}`;
}

function previewRailPath(inputCount: number, outputCount: number): string {
  const rails = [
    'M 4 13 a 8 8 0 0 1 8 -8',
    'M 4 115 a 8 8 0 0 0 8 8',
    'M 188 13 a 8 8 0 0 0 -8 -8',
    'M 188 115 a 8 8 0 0 1 -8 8',
    'M 4 4 a 8 8 0 0 0 -8 -8',
    'M 188 4 a 8 8 0 0 1 8 -8',
    'M 4 124 a 8 8 0 0 1 -8 8',
    'M 188 124 a 8 8 0 0 0 8 8',
  ];
  for (let index = 0; index < inputCount; index += 1) {
    const offset = stationOffset(index);
    const bend = 8 + index;
    rails.push(
      'M 4 13',
      curve([0, bend], [0, -bend], [offset, 20]),
      'l 0 60',
      curve([0, bend], [0, -bend], [-offset, 20]),
    );
  }
  for (let index = 0; index < outputCount; index += 1) {
    const offset = -stationOffset(index);
    const bend = 8 + index;
    rails.push(
      'M 188 13',
      curve([0, bend], [0, -bend], [offset, 20]),
      'l 0 60',
      curve([0, bend], [0, -bend], [-offset, 20]),
    );
  }
  return rails.join(' ');
}

/** A schematic preview of the concrete station fan generated by buildRailBrick. */
export function RailBlueprintPreview({
  size: [inputCount, outputCount],
}: {
  size: [number, number];
}) {
  const stationSummary = `${inputCount} input and ${outputCount} output stations`;
  return (
    <figure class="rail-blueprint-preview">
      <figcaption>
        <span>Rail brick</span>
        <span class="rail-blueprint-preview-caption">
          {inputCount} input, {outputCount} output blueprint
        </span>
      </figcaption>
      <svg
        viewBox={`0 0 ${viewBoxWidth} 128`}
        role="img"
        aria-label={`Rail blueprint: ${stationSummary}`}
      >
        <title>Rail blueprint: {stationSummary}</title>
        <desc>
          A rail brick with input station fans on the left and output station fans on the right.
        </desc>
        <rect class="rail-blueprint-preview-floor" x="0" y="0" width="192" height="128" />
        <g class="rail-blueprint-preview-border">
          <rect x="3" y="4" width="2" height="120" />
          <rect x="187" y="4" width="2" height="120" />
          <rect x="0" y="4" width="192" height="2" />
          <rect x="0" y="122" width="192" height="2" />
        </g>
        <path class="rail-blueprint-preview-path" d={previewRailPath(inputCount, outputCount)} />
        {(['input', 'output'] as const).flatMap((side) =>
          Array.from({ length: side === 'input' ? inputCount : outputCount }, (_, index) => {
            const { x, y } = stationPosition(side, index);
            return (
              <circle
                class="rail-blueprint-preview-stop"
                key={`${side}-${index}`}
                cx={x}
                cy={y}
                r="1.8"
                data-blueprint-station={`${side}:${index + 1}`}
              >
                <title>
                  {side === 'input' ? 'Input' : 'Output'} station {index + 1}
                </title>
              </circle>
            );
          }),
        )}
      </svg>
    </figure>
  );
}
